on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Test installation.
    steps:
      - uses: actions/checkout@v3

      - id: install-version
        uses: diku-dk/install-futhark@HEAD
        with:
          version: '0.22.3'
      - id: install-no-version
        uses: diku-dk/install-futhark@HEAD
      - id: install-latest
        uses: diku-dk/install-futhark@HEAD
        with:
          version: 'latest'
